{% set pyproject = load_file_data('pyproject.toml') %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = pyproject.get('tool', {}).get('setuptools', {}).get('version') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: rose
  script:
    - python -m pip install . -vv

requirements:
  host:
    - python x.x
    - setuptools

  build:
    - python x.x
    - setuptools

  run:
    - python x.x
test:
  imports:
    - openalea.rose
    - openalea.rose.mockup
  requires:
    - pytest
  source_files:
    - test/**
  commands:
    - pytest

about:
  home: {{ home }}
  description: {{ description }}
  license: CeCILL-C
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pradal
