{% set pyproject = load_file_data('pyproject.toml') %}
{% set description_pkg = pyproject.get('project').get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

{% set major = load_file_regex(
  load_file="src/openalea/rose/version.py",
  regex_pattern='major = (.+)') %}
{% set minor = load_file_regex(
  load_file="src/openalea/rose/version.py",
  regex_pattern='minor = (.+)') %}
{% set post = load_file_regex(
  load_file="src/openalea/rose/version.py",
  regex_pattern='post = (.+)') %}

{% set version = major[ 1 ]+'.'+minor[ 1 ]+'.'+post[ 1 ] %}

package:
  name: openalea.rose
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  string: rose
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm

  build:
    - python
    - setuptools

  run:
    - python x.x
    - openalea.plantgl
    - openalea.mtg
    - openalea.core
    - importlib_resources

test:
  imports:
    - openalea.rose
    - openalea.rose.mockup
  requires:
    - pytest
  source_files:
    - test/**
  commands:
    - pytest

about:
  home: {{ home }}
  description: {{ description_pkg }}
  license: Cecill-C License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pradal
