{% set pyproject = load_file_data('pyproject.toml') %}
{% set name = pyproject.get('project', {}).get('name') %}
{% set description = pyproject.get('project', {}).get('description') %}
{% set license = pyproject.get('project', {}).get('license') %}
{% set version = pyproject.get('project', {}).get('version') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: rose
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools

  build:
    - python
    - setuptools

  run:
    - python x.x
    - openalea.plantgl
    - openalea.mtg

test:
  imports:
    - openalea.rose
    - openalea.rose.mockup
  requires:
    - pytest
  source_files:
    - test/**
  commands:
    - pytest

about:
  home: {{ home }}
  description: {{ description }}
  license: {{ license }}
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pradal
